# Generated by Django 5.2.5 on 2025-09-06 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('File_Name', models.CharField(max_length=100)),
                ('Upload_File', models.FileField(upload_to='')),
            ],
        ),
    ]
