# Generated by Django 5.2.5 on 2025-08-24 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('age', models.IntegerField()),
                ('Email', models.EmailField(max_length=20)),
                ('Branch', models.CharField(choices=[('CS', 'Computer Science'), ('AI', 'Airtificial Intelligence'), ('ML', 'Machine learning')], max_length=50)),
                ('Date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
