# Generated by Django 5.2.5 on 2025-08-24 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='Gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'FeMale'), ('O', 'Others')], default='M', max_length=10),
        ),
    ]
