# Generated by Django 5.2.5 on 2025-08-30 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_student_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='Branch',
            new_name='branch',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='Date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='Gender',
            new_name='gender',
        ),
        migrations.RemoveField(
            model_name='student',
            name='Email',
        ),
        migrations.AddField(
            model_name='student',
            name='email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
    ]
