# Generated by Django 5.2.5 on 2025-08-30 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_rename_branch_student_branch_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='date',
            new_name='Date',
        ),
    ]
